# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_mainDecQgI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QHeaderView, QLabel,
    QLayout, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStackedWidget, QStatusBar, QTabWidget, QTableView,
    QTextBrowser, QVBoxLayout, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1091, 938)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1091, 938))
        MainWindow.setMaximumSize(QSize(1091, 938))
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.actionOpen_Video = QAction(MainWindow)
        self.actionOpen_Video.setObjectName(u"actionOpen_Video")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.actionScale_Bar = QAction(MainWindow)
        self.actionScale_Bar.setObjectName(u"actionScale_Bar")
        self.actionAdjustments = QAction(MainWindow)
        self.actionAdjustments.setObjectName(u"actionAdjustments")
        self.actionMain = QAction(MainWindow)
        self.actionMain.setObjectName(u"actionMain")
        self.actionData = QAction(MainWindow)
        self.actionData.setObjectName(u"actionData")
        self.actionPoints = QAction(MainWindow)
        self.actionPoints.setObjectName(u"actionPoints")
        self.actionBounding_Boxes = QAction(MainWindow)
        self.actionBounding_Boxes.setObjectName(u"actionBounding_Boxes")
        self.actionPoints_2 = QAction(MainWindow)
        self.actionPoints_2.setObjectName(u"actionPoints_2")
        self.actionPoints_2.setCheckable(True)
        self.actionBounding_Boxes_2 = QAction(MainWindow)
        self.actionBounding_Boxes_2.setObjectName(u"actionBounding_Boxes_2")
        self.actionBounding_Boxes_2.setCheckable(True)
        self.actionBounding_Boxes_2.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabs = QStackedWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(-1, -1, 1091, 901))
        self.mainView = QWidget()
        self.mainView.setObjectName(u"mainView")
        self.frame = QFrame(self.mainView)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 20, 661, 551))
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(8)
        self.frame.setMidLineWidth(0)
        self.frame_8 = QFrame(self.frame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 641, 31))
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_2 = QLabel(self.frame_8)
        self.trackingTitle_2.setObjectName(u"trackingTitle_2")
        self.trackingTitle_2.setGeometry(QRect(0, 0, 641, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.trackingTitle_2.setFont(font)
        self.trackingTitle_2.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_2.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_2.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gridLayoutWidget = QWidget(self.frame)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 50, 642, 491))
        self.videoLayout = QGridLayout(self.gridLayoutWidget)
        self.videoLayout.setObjectName(u"videoLayout")
        self.videoLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.video_1 = QPushButton(self.gridLayoutWidget)
        self.video_1.setObjectName(u"video_1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.video_1.sizePolicy().hasHeightForWidth())
        self.video_1.setSizePolicy(sizePolicy1)
        self.video_1.setMaximumSize(QSize(640, 480))
        self.video_1.setIconSize(QSize(75, 24))
        self.video_1.setCheckable(True)
        self.video_1.setFlat(False)

        self.videoLayout.addWidget(self.video_1, 0, 0, 1, 1)

        self.testButton = QPushButton(self.mainView)
        self.testButton.setObjectName(u"testButton")
        self.testButton.setGeometry(QRect(990, 570, 75, 24))
        self.frame_4 = QFrame(self.mainView)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(20, 600, 1051, 281))
        self.frame_4.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.printOutput = QTextBrowser(self.frame_4)
        self.printOutput.setObjectName(u"printOutput")
        self.printOutput.setGeometry(QRect(10, 50, 1031, 221))
        self.printOutput.setAcceptDrops(False)
        self.printOutput.setOpenLinks(False)
        self.frame_7 = QFrame(self.frame_4)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 10, 1031, 31))
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.consoleOutputTitle = QLabel(self.frame_7)
        self.consoleOutputTitle.setObjectName(u"consoleOutputTitle")
        self.consoleOutputTitle.setGeometry(QRect(0, 0, 1031, 31))
        self.consoleOutputTitle.setFont(font)
        self.consoleOutputTitle.setFrameShape(QFrame.Shape.NoFrame)
        self.consoleOutputTitle.setFrameShadow(QFrame.Shadow.Raised)
        self.consoleOutputTitle.setTextFormat(Qt.TextFormat.RichText)
        self.consoleOutputTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_3 = QFrame(self.mainView)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(700, 310, 371, 261))
        self.frame_3.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(8)
        self.frame_5 = QFrame(self.frame_3)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 10, 347, 31))
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle = QLabel(self.frame_5)
        self.trackingTitle.setObjectName(u"trackingTitle")
        self.trackingTitle.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy.setHeightForWidth(self.trackingTitle.sizePolicy().hasHeightForWidth())
        self.trackingTitle.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setUnderline(False)
        self.trackingTitle.setFont(font1)
        self.trackingTitle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.trackingTitle.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.verticalLayoutWidget_3 = QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 50, 351, 201))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.threshold_2 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_2.setObjectName(u"threshold_2")
        font2 = QFont()
        font2.setPointSize(12)
        self.threshold_2.setFont(font2)
        self.threshold_2.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_2.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_2.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_7.addWidget(self.threshold_2)

        self.subBackMethod = QComboBox(self.verticalLayoutWidget_3)
        self.subBackMethod.addItem("")
        self.subBackMethod.addItem("")
        self.subBackMethod.setObjectName(u"subBackMethod")
        self.subBackMethod.setEnabled(False)
        self.subBackMethod.setMaximumSize(QSize(75, 16777215))

        self.horizontalLayout_7.addWidget(self.subBackMethod)


        self.verticalLayout_5.addLayout(self.horizontalLayout_7)

        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.subBackToggle = QCheckBox(self.verticalLayoutWidget_3)
        self.subBackToggle.setObjectName(u"subBackToggle")
        self.subBackToggle.setFont(font2)

        self.horizontalLayout_4.addWidget(self.subBackToggle)

        self.subBackSlider = QSlider(self.verticalLayoutWidget_3)
        self.subBackSlider.setObjectName(u"subBackSlider")
        self.subBackSlider.setEnabled(False)
        self.subBackSlider.setMaximum(100)
        self.subBackSlider.setOrientation(Qt.Orientation.Horizontal)
        self.subBackSlider.setInvertedAppearance(False)
        self.subBackSlider.setInvertedControls(False)
        self.subBackSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.subBackSlider.setTickInterval(10)

        self.horizontalLayout_4.addWidget(self.subBackSlider)

        self.subBackValue = QSpinBox(self.verticalLayoutWidget_3)
        self.subBackValue.setObjectName(u"subBackValue")
        self.subBackValue.setEnabled(False)
        self.subBackValue.setMinimumSize(QSize(100, 0))
        self.subBackValue.setFont(font2)
        self.subBackValue.setMaximum(100)

        self.horizontalLayout_4.addWidget(self.subBackValue)


        self.verticalLayout_6.addLayout(self.horizontalLayout_4)


        self.verticalLayout_5.addLayout(self.verticalLayout_6)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.threshold_3 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_3.setObjectName(u"threshold_3")
        self.threshold_3.setFont(font2)
        self.threshold_3.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_3.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_3.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_8.addWidget(self.threshold_3)

        self.cf = QLabel(self.verticalLayoutWidget_3)
        self.cf.setObjectName(u"cf")
        self.cf.setEnabled(False)
        self.cf.setMaximumSize(QSize(20, 16777215))
        self.cf.setFont(font2)
        self.cf.setFrameShape(QFrame.Shape.NoFrame)
        self.cf.setFrameShadow(QFrame.Shadow.Raised)
        self.cf.setTextFormat(Qt.TextFormat.RichText)
        self.cf.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.cf)

        self.consecutiveFramesValue = QSpinBox(self.verticalLayoutWidget_3)
        self.consecutiveFramesValue.setObjectName(u"consecutiveFramesValue")
        self.consecutiveFramesValue.setEnabled(False)
        self.consecutiveFramesValue.setMinimumSize(QSize(75, 0))
        self.consecutiveFramesValue.setMaximumSize(QSize(75, 16777215))
        self.consecutiveFramesValue.setFont(font2)
        self.consecutiveFramesValue.setMinimum(0)
        self.consecutiveFramesValue.setMaximum(100)

        self.horizontalLayout_8.addWidget(self.consecutiveFramesValue)


        self.verticalLayout_5.addLayout(self.horizontalLayout_8)

        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frameDiffToggle = QCheckBox(self.verticalLayoutWidget_3)
        self.frameDiffToggle.setObjectName(u"frameDiffToggle")
        self.frameDiffToggle.setFont(font2)

        self.horizontalLayout_5.addWidget(self.frameDiffToggle)

        self.frameDiffSlider = QSlider(self.verticalLayoutWidget_3)
        self.frameDiffSlider.setObjectName(u"frameDiffSlider")
        self.frameDiffSlider.setEnabled(False)
        self.frameDiffSlider.setMinimum(0)
        self.frameDiffSlider.setMaximum(100)
        self.frameDiffSlider.setValue(25)
        self.frameDiffSlider.setOrientation(Qt.Orientation.Horizontal)
        self.frameDiffSlider.setInvertedAppearance(False)
        self.frameDiffSlider.setInvertedControls(False)
        self.frameDiffSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.frameDiffSlider.setTickInterval(10)

        self.horizontalLayout_5.addWidget(self.frameDiffSlider)

        self.frameDiffValue = QSpinBox(self.verticalLayoutWidget_3)
        self.frameDiffValue.setObjectName(u"frameDiffValue")
        self.frameDiffValue.setEnabled(False)
        self.frameDiffValue.setMinimumSize(QSize(100, 0))
        self.frameDiffValue.setFont(font2)
        self.frameDiffValue.setMinimum(0)
        self.frameDiffValue.setMaximum(100)

        self.horizontalLayout_5.addWidget(self.frameDiffValue)


        self.verticalLayout_7.addLayout(self.horizontalLayout_5)


        self.verticalLayout_5.addLayout(self.verticalLayout_7)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.threshold_4 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_4.setObjectName(u"threshold_4")
        self.threshold_4.setFont(font2)
        self.threshold_4.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_4.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_4.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_9.addWidget(self.threshold_4)

        self.contDetMethod = QComboBox(self.verticalLayoutWidget_3)
        self.contDetMethod.setObjectName(u"contDetMethod")
        self.contDetMethod.setEnabled(False)
        self.contDetMethod.setMaximumSize(QSize(75, 16777215))

        self.horizontalLayout_9.addWidget(self.contDetMethod)


        self.verticalLayout_5.addLayout(self.horizontalLayout_9)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.contDetectSlider = QSlider(self.verticalLayoutWidget_3)
        self.contDetectSlider.setObjectName(u"contDetectSlider")
        self.contDetectSlider.setEnabled(False)
        self.contDetectSlider.setFont(font2)
        self.contDetectSlider.setMaximum(100)
        self.contDetectSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contDetectSlider.setInvertedAppearance(False)
        self.contDetectSlider.setInvertedControls(False)
        self.contDetectSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contDetectSlider.setTickInterval(10)

        self.horizontalLayout_6.addWidget(self.contDetectSlider)

        self.contDetectValue = QSpinBox(self.verticalLayoutWidget_3)
        self.contDetectValue.setObjectName(u"contDetectValue")
        self.contDetectValue.setEnabled(False)
        self.contDetectValue.setMinimumSize(QSize(100, 0))
        self.contDetectValue.setFont(font2)
        self.contDetectValue.setMaximum(100)

        self.horizontalLayout_6.addWidget(self.contDetectValue)


        self.verticalLayout_8.addLayout(self.horizontalLayout_6)


        self.verticalLayout_5.addLayout(self.verticalLayout_8)

        self.frame_2 = QFrame(self.mainView)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(700, 20, 371, 261))
        self.frame_2.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(8)
        self.verticalLayoutWidget_2 = QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 50, 351, 201))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.threshold = QLabel(self.verticalLayoutWidget_2)
        self.threshold.setObjectName(u"threshold")
        self.threshold.setFont(font2)
        self.threshold.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold.setTextFormat(Qt.TextFormat.RichText)
        self.threshold.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.threshold)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.thresholdToggle = QCheckBox(self.verticalLayoutWidget_2)
        self.thresholdToggle.setObjectName(u"thresholdToggle")
        self.thresholdToggle.setFont(font2)

        self.horizontalLayout.addWidget(self.thresholdToggle)

        self.thresholdSlider = QSlider(self.verticalLayoutWidget_2)
        self.thresholdSlider.setObjectName(u"thresholdSlider")
        self.thresholdSlider.setEnabled(False)
        self.thresholdSlider.setMaximum(100)
        self.thresholdSlider.setOrientation(Qt.Orientation.Horizontal)
        self.thresholdSlider.setInvertedAppearance(False)
        self.thresholdSlider.setInvertedControls(False)
        self.thresholdSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.thresholdSlider.setTickInterval(10)

        self.horizontalLayout.addWidget(self.thresholdSlider)

        self.thresholdValue = QSpinBox(self.verticalLayoutWidget_2)
        self.thresholdValue.setObjectName(u"thresholdValue")
        self.thresholdValue.setEnabled(False)
        self.thresholdValue.setMinimumSize(QSize(100, 0))
        self.thresholdValue.setFont(font2)
        self.thresholdValue.setMaximum(100)

        self.horizontalLayout.addWidget(self.thresholdValue)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.contrast = QLabel(self.verticalLayoutWidget_2)
        self.contrast.setObjectName(u"contrast")
        self.contrast.setFont(font2)
        self.contrast.setFrameShape(QFrame.Shape.NoFrame)
        self.contrast.setFrameShadow(QFrame.Shadow.Raised)
        self.contrast.setTextFormat(Qt.TextFormat.RichText)
        self.contrast.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.contrast)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.contrastToggle = QCheckBox(self.verticalLayoutWidget_2)
        self.contrastToggle.setObjectName(u"contrastToggle")
        self.contrastToggle.setFont(font2)

        self.horizontalLayout_2.addWidget(self.contrastToggle)

        self.contrastSlider = QSlider(self.verticalLayoutWidget_2)
        self.contrastSlider.setObjectName(u"contrastSlider")
        self.contrastSlider.setEnabled(False)
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contrastSlider.setInvertedAppearance(False)
        self.contrastSlider.setInvertedControls(False)
        self.contrastSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contrastSlider.setTickInterval(10)

        self.horizontalLayout_2.addWidget(self.contrastSlider)

        self.contrastValue = QSpinBox(self.verticalLayoutWidget_2)
        self.contrastValue.setObjectName(u"contrastValue")
        self.contrastValue.setEnabled(False)
        self.contrastValue.setMinimumSize(QSize(100, 0))
        self.contrastValue.setFont(font2)
        self.contrastValue.setMinimum(-100)
        self.contrastValue.setMaximum(100)

        self.horizontalLayout_2.addWidget(self.contrastValue)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)


        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.contour = QLabel(self.verticalLayoutWidget_2)
        self.contour.setObjectName(u"contour")
        self.contour.setFont(font2)
        self.contour.setFrameShape(QFrame.Shape.NoFrame)
        self.contour.setFrameShadow(QFrame.Shadow.Raised)
        self.contour.setTextFormat(Qt.TextFormat.RichText)
        self.contour.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_4.addWidget(self.contour)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.contourToggle = QCheckBox(self.verticalLayoutWidget_2)
        self.contourToggle.setObjectName(u"contourToggle")
        self.contourToggle.setFont(font2)

        self.horizontalLayout_3.addWidget(self.contourToggle)

        self.contourSlider = QSlider(self.verticalLayoutWidget_2)
        self.contourSlider.setObjectName(u"contourSlider")
        self.contourSlider.setEnabled(False)
        self.contourSlider.setFont(font2)
        self.contourSlider.setMinimum(-100)
        self.contourSlider.setMaximum(100)
        self.contourSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contourSlider.setInvertedAppearance(False)
        self.contourSlider.setInvertedControls(False)
        self.contourSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contourSlider.setTickInterval(10)

        self.horizontalLayout_3.addWidget(self.contourSlider)

        self.contourValue = QSpinBox(self.verticalLayoutWidget_2)
        self.contourValue.setObjectName(u"contourValue")
        self.contourValue.setEnabled(False)
        self.contourValue.setMinimumSize(QSize(100, 0))
        self.contourValue.setFont(font2)
        self.contourValue.setMinimum(-100)
        self.contourValue.setMaximum(100)

        self.horizontalLayout_3.addWidget(self.contourValue)


        self.verticalLayout_4.addLayout(self.horizontalLayout_3)


        self.verticalLayout_2.addLayout(self.verticalLayout_4)

        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 10, 351, 31))
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_3 = QLabel(self.frame_6)
        self.trackingTitle_3.setObjectName(u"trackingTitle_3")
        self.trackingTitle_3.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy.setHeightForWidth(self.trackingTitle_3.sizePolicy().hasHeightForWidth())
        self.trackingTitle_3.setSizePolicy(sizePolicy)
        self.trackingTitle_3.setFont(font1)
        self.trackingTitle_3.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_3.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_3.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayoutWidget_4 = QWidget(self.mainView)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(20, 570, 661, 31))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.record = QPushButton(self.horizontalLayoutWidget_4)
        self.record.setObjectName(u"record")
        self.record.setMaximumSize(QSize(100, 16777215))
        self.record.setCheckable(True)

        self.horizontalLayout_10.addWidget(self.record)

        self.tabs.addWidget(self.mainView)
        self.frame.raise_()
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.testButton.raise_()
        self.dataView = QWidget()
        self.dataView.setObjectName(u"dataView")
        self.frame_9 = QFrame(self.dataView)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(20, 20, 1061, 551))
        self.frame_9.setAcceptDrops(True)
        self.frame_9.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_9.setLineWidth(8)
        self.frame_9.setMidLineWidth(0)
        self.frame_10 = QFrame(self.frame_9)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 10, 1041, 31))
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_4 = QLabel(self.frame_10)
        self.trackingTitle_4.setObjectName(u"trackingTitle_4")
        self.trackingTitle_4.setGeometry(QRect(0, 0, 1041, 31))
        self.trackingTitle_4.setFont(font)
        self.trackingTitle_4.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_4.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_4.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.dataTabs_2 = QTabWidget(self.frame_9)
        self.dataTabs_2.setObjectName(u"dataTabs_2")
        self.dataTabs_2.setGeometry(QRect(10, 50, 1041, 491))
        self.dataTabs_2.setTabPosition(QTabWidget.TabPosition.North)
        self.dataTabs_2.setTabShape(QTabWidget.TabShape.Rounded)
        self.dataTabs_2.setElideMode(Qt.TextElideMode.ElideNone)
        self.dataTabs_2.setDocumentMode(False)
        self.dataTabs_2.setTabsClosable(False)
        self.dataTabs_2.setMovable(True)
        self.dataTabs_2.setTabBarAutoHide(False)
        self.Summary = QWidget()
        self.Summary.setObjectName(u"Summary")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Summary.sizePolicy().hasHeightForWidth())
        self.Summary.setSizePolicy(sizePolicy2)
        self.video2Plot_2 = PlotWidget(self.Summary)
        self.video2Plot_2.setObjectName(u"video2Plot_2")
        self.video2Plot_2.setGeometry(QRect(0, 0, 1041, 471))
        self.dataTabs_2.addTab(self.Summary, "")
        self.video1_2 = QWidget()
        self.video1_2.setObjectName(u"video1_2")
        self.plot1 = PlotWidget(self.video1_2)
        self.plot1.setObjectName(u"plot1")
        self.plot1.setGeometry(QRect(0, 0, 1041, 471))
        self.dataTabs_2.addTab(self.video1_2, "")
        self.video2_2 = QWidget()
        self.video2_2.setObjectName(u"video2_2")
        self.video2Plot = PlotWidget(self.video2_2)
        self.video2Plot.setObjectName(u"video2Plot")
        self.video2Plot.setGeometry(QRect(0, 0, 1041, 471))
        self.dataTabs_2.addTab(self.video2_2, "")
        self.frame_11 = QFrame(self.dataView)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(20, 590, 1061, 291))
        self.frame_11.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_11.setLineWidth(8)
        self.frame_12 = QFrame(self.frame_11)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(10, 10, 1041, 31))
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_5 = QLabel(self.frame_12)
        self.trackingTitle_5.setObjectName(u"trackingTitle_5")
        self.trackingTitle_5.setGeometry(QRect(0, 0, 1041, 31))
        sizePolicy.setHeightForWidth(self.trackingTitle_5.sizePolicy().hasHeightForWidth())
        self.trackingTitle_5.setSizePolicy(sizePolicy)
        self.trackingTitle_5.setFont(font1)
        self.trackingTitle_5.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_5.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_5.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.dataTabs = QTabWidget(self.frame_11)
        self.dataTabs.setObjectName(u"dataTabs")
        self.dataTabs.setGeometry(QRect(10, 50, 1041, 231))
        self.dataTabs.setTabShape(QTabWidget.TabShape.Rounded)
        self.dataTabs.setDocumentMode(False)
        self.dataTabs.setTabsClosable(False)
        self.dataTabs.setMovable(False)
        self.dataTabs.setTabBarAutoHide(False)
        self.video1 = QWidget()
        self.video1.setObjectName(u"video1")
        self.video1Data = QTableView(self.video1)
        self.video1Data.setObjectName(u"video1Data")
        self.video1Data.setGeometry(QRect(0, 0, 1041, 201))
        self.dataTabs.addTab(self.video1, "")
        self.video2 = QWidget()
        self.video2.setObjectName(u"video2")
        self.video2Data = QTableView(self.video2)
        self.video2Data.setObjectName(u"video2Data")
        self.video2Data.setGeometry(QRect(0, 0, 1041, 201))
        sizePolicy.setHeightForWidth(self.video2Data.sizePolicy().hasHeightForWidth())
        self.video2Data.setSizePolicy(sizePolicy)
        self.dataTabs.addTab(self.video2, "")
        self.tabs.addWidget(self.dataView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1091, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuClear = QMenu(self.menubar)
        self.menuClear.setObjectName(u"menuClear")
        self.menuClear.setTearOffEnabled(False)
        self.menuMain = QMenu(self.menubar)
        self.menuMain.setObjectName(u"menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menuMain.menuAction())
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionSave)
        self.menuClear.addAction(self.actionClear)
        self.menuClear.addAction(self.actionAdjustments)
        self.menuClear.addAction(self.actionScale_Bar)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionMain)
        self.menuMain.addAction(self.actionData)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionPoints_2)
        self.menuMain.addAction(self.actionBounding_Boxes_2)

        self.retranslateUi(MainWindow)
        self.contourSlider.valueChanged.connect(self.contourValue.setValue)
        self.contrastSlider.valueChanged.connect(self.contrastValue.setValue)
        self.thresholdSlider.valueChanged.connect(self.thresholdValue.setValue)
        self.contourValue.valueChanged.connect(self.contourSlider.setValue)
        self.contrastValue.valueChanged.connect(self.contrastSlider.setValue)
        self.thresholdValue.valueChanged.connect(self.thresholdSlider.setValue)
        self.contourToggle.toggled.connect(self.contourSlider.setEnabled)
        self.contourToggle.toggled.connect(self.contourValue.setEnabled)
        self.thresholdToggle.toggled.connect(self.thresholdSlider.setEnabled)
        self.thresholdToggle.toggled.connect(self.thresholdValue.setEnabled)
        self.contrastToggle.toggled.connect(self.contrastSlider.setEnabled)
        self.contrastToggle.toggled.connect(self.contrastValue.setEnabled)
        self.contDetectSlider.valueChanged.connect(self.contDetectValue.setValue)
        self.contDetectValue.valueChanged.connect(self.contDetectSlider.setValue)
        self.frameDiffSlider.valueChanged.connect(self.frameDiffValue.setValue)
        self.frameDiffToggle.toggled.connect(self.frameDiffSlider.setEnabled)
        self.frameDiffValue.valueChanged.connect(self.frameDiffSlider.setValue)
        self.subBackValue.valueChanged.connect(self.subBackSlider.setValue)
        self.subBackToggle.toggled.connect(self.subBackSlider.setEnabled)
        self.subBackSlider.valueChanged.connect(self.subBackValue.setValue)
        self.subBackToggle.toggled.connect(self.subBackValue.setEnabled)
        self.frameDiffToggle.toggled.connect(self.frameDiffValue.setEnabled)
        self.subBackToggle.toggled.connect(self.subBackMethod.setEnabled)
        self.frameDiffToggle.toggled.connect(self.consecutiveFramesValue.setEnabled)
        self.frameDiffToggle.toggled.connect(self.cf.setEnabled)
        self.record.toggled.connect(self.contDetectSlider.setEnabled)
        self.record.toggled.connect(self.contDetMethod.setEnabled)
        self.record.toggled.connect(self.contDetectValue.setEnabled)

        self.tabs.setCurrentIndex(0)
        self.dataTabs_2.setCurrentIndex(1)
        self.dataTabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen_Video.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.actionScale_Bar.setText(QCoreApplication.translate("MainWindow", u"Scale Bar", None))
        self.actionAdjustments.setText(QCoreApplication.translate("MainWindow", u"Adjustments", None))
        self.actionMain.setText(QCoreApplication.translate("MainWindow", u"Main", None))
        self.actionData.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.actionPoints.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.actionPoints_2.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes_2.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.trackingTitle_2.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.video_1.setText("")
        self.testButton.setText(QCoreApplication.translate("MainWindow", u"Test!", None))
        self.consoleOutputTitle.setText(QCoreApplication.translate("MainWindow", u"Console Output", None))
        self.trackingTitle.setText(QCoreApplication.translate("MainWindow", u"Tracking", None))
        self.threshold_2.setText(QCoreApplication.translate("MainWindow", u"Subtract Background", None))
        self.subBackMethod.setItemText(0, QCoreApplication.translate("MainWindow", u"KNN", None))
        self.subBackMethod.setItemText(1, QCoreApplication.translate("MainWindow", u"MOG2", None))

        self.subBackToggle.setText("")
        self.threshold_3.setText(QCoreApplication.translate("MainWindow", u"Frame Differencing", None))
        self.cf.setText(QCoreApplication.translate("MainWindow", u"CF", None))
        self.frameDiffToggle.setText("")
        self.threshold_4.setText(QCoreApplication.translate("MainWindow", u"Persistence", None))
        self.threshold.setText(QCoreApplication.translate("MainWindow", u"Threshold", None))
        self.thresholdToggle.setText("")
        self.contrast.setText(QCoreApplication.translate("MainWindow", u"Contrast", None))
        self.contrastToggle.setText("")
        self.contour.setText(QCoreApplication.translate("MainWindow", u"Emboss", None))
        self.contourToggle.setText("")
        self.trackingTitle_3.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.record.setText(QCoreApplication.translate("MainWindow", u"Record Data", None))
        self.trackingTitle_4.setText(QCoreApplication.translate("MainWindow", u"Graph Title", None))
        self.dataTabs_2.setTabText(self.dataTabs_2.indexOf(self.Summary), QCoreApplication.translate("MainWindow", u"Summary", None))
        self.dataTabs_2.setTabText(self.dataTabs_2.indexOf(self.video1_2), QCoreApplication.translate("MainWindow", u"video1", None))
        self.dataTabs_2.setTabText(self.dataTabs_2.indexOf(self.video2_2), QCoreApplication.translate("MainWindow", u"video2", None))
        self.trackingTitle_5.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.dataTabs.setTabText(self.dataTabs.indexOf(self.video1), QCoreApplication.translate("MainWindow", u"video1", None))
        self.dataTabs.setTabText(self.dataTabs.indexOf(self.video2), QCoreApplication.translate("MainWindow", u"video2", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuClear.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuMain.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

