# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main_scrollablejcSNHN.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QTabWidget, QTextBrowser, QVBoxLayout,
    QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1091, 938)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(1091, 938))
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.actionOpen_Video = QAction(MainWindow)
        self.actionOpen_Video.setObjectName(u"actionOpen_Video")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        self.actionPoints = QAction(MainWindow)
        self.actionPoints.setObjectName(u"actionPoints")
        self.actionBounding_Boxes = QAction(MainWindow)
        self.actionBounding_Boxes.setObjectName(u"actionBounding_Boxes")
        self.actionPoints_2 = QAction(MainWindow)
        self.actionPoints_2.setObjectName(u"actionPoints_2")
        self.actionPoints_2.setCheckable(True)
        self.actionBounding_Boxes_2 = QAction(MainWindow)
        self.actionBounding_Boxes_2.setObjectName(u"actionBounding_Boxes_2")
        self.actionBounding_Boxes_2.setCheckable(True)
        self.actionBounding_Boxes_2.setChecked(True)
        self.actionFPS = QAction(MainWindow)
        self.actionFPS.setObjectName(u"actionFPS")
        self.actionFPS.setCheckable(True)
        self.actionOriginal_Frame = QAction(MainWindow)
        self.actionOriginal_Frame.setObjectName(u"actionOriginal_Frame")
        self.actionOriginal_Frame.setCheckable(True)
        self.actionCollate_Data_NPM = QAction(MainWindow)
        self.actionCollate_Data_NPM.setObjectName(u"actionCollate_Data_NPM")
        self.actionDetails = QAction(MainWindow)
        self.actionDetails.setObjectName(u"actionDetails")
        self.actionDetails.setCheckable(True)
        self.actionDirection = QAction(MainWindow)
        self.actionDirection.setObjectName(u"actionDirection")
        self.actionDirection.setCheckable(True)
        self.actionDirection.setChecked(True)
        self.actionSpeed = QAction(MainWindow)
        self.actionSpeed.setObjectName(u"actionSpeed")
        self.actionSpeed.setCheckable(True)
        self.actionSpeed.setChecked(True)
        self.actionAngular_Velocity = QAction(MainWindow)
        self.actionAngular_Velocity.setObjectName(u"actionAngular_Velocity")
        self.actionAngular_Velocity.setCheckable(True)
        self.actionAngular_Velocity.setChecked(True)
        self.actionMedian_Velocity = QAction(MainWindow)
        self.actionMedian_Velocity.setObjectName(u"actionMedian_Velocity")
        self.actionMedian_Velocity_2 = QAction(MainWindow)
        self.actionMedian_Velocity_2.setObjectName(u"actionMedian_Velocity_2")
        self.actionMedian_Velocity_2.setCheckable(True)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionShow = QAction(MainWindow)
        self.actionShow.setObjectName(u"actionShow")
        self.actionShow.setCheckable(True)
        self.actionShow.setChecked(True)
        self.actionLock_Size = QAction(MainWindow)
        self.actionLock_Size.setObjectName(u"actionLock_Size")
        self.actionLock_Size.setCheckable(True)
        self.actionAlignment_Angle = QAction(MainWindow)
        self.actionAlignment_Angle.setObjectName(u"actionAlignment_Angle")
        self.actionAlignment_Angle.setCheckable(True)
        self.actionAlignment_Angle.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setMaximumSize(QSize(1091, 901))
        self.scrollArea.setFrameShape(QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -4, 1061, 870))
        self.verticalLayout_3 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMinimumSize(QSize(660, 570))
        self.frame.setMaximumSize(QSize(660, 570))
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(8)
        self.frame.setMidLineWidth(0)
        self.frame_8 = QFrame(self.frame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 10, 641, 31))
        sizePolicy1.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy1)
        self.frame_8.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_2 = QLabel(self.frame_8)
        self.trackingTitle_2.setObjectName(u"trackingTitle_2")
        self.trackingTitle_2.setGeometry(QRect(0, 0, 641, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.trackingTitle_2.setFont(font)
        self.trackingTitle_2.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_2.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_2.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gridLayoutWidget = QWidget(self.frame)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 50, 642, 491))
        self.videoLayout = QGridLayout(self.gridLayoutWidget)
        self.videoLayout.setObjectName(u"videoLayout")
        self.videoLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.videoLayout.setContentsMargins(0, 0, 0, 0)
        self.video_1 = QPushButton(self.gridLayoutWidget)
        self.video_1.setObjectName(u"video_1")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.video_1.sizePolicy().hasHeightForWidth())
        self.video_1.setSizePolicy(sizePolicy2)
        self.video_1.setMaximumSize(QSize(640, 480))
        self.video_1.setIconSize(QSize(75, 24))
        self.video_1.setCheckable(True)
        self.video_1.setFlat(False)

        self.videoLayout.addWidget(self.video_1, 0, 0, 1, 1)

        self.horizontalLayoutWidget_2 = QWidget(self.frame)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(9, 540, 641, 31))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.record = QPushButton(self.horizontalLayoutWidget_2)
        self.record.setObjectName(u"record")
        self.record.setMaximumSize(QSize(100, 16777215))
        self.record.setCheckable(True)

        self.horizontalLayout_10.addWidget(self.record)


        self.horizontalLayout_3.addWidget(self.frame)

        self.frame_2 = QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy1.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy1)
        self.frame_2.setMinimumSize(QSize(370, 570))
        self.frame_2.setMaximumSize(QSize(370, 570))
        self.frame_2.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(8)
        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 10, 351, 31))
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle_3 = QLabel(self.frame_6)
        self.trackingTitle_3.setObjectName(u"trackingTitle_3")
        self.trackingTitle_3.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy1.setHeightForWidth(self.trackingTitle_3.sizePolicy().hasHeightForWidth())
        self.trackingTitle_3.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setUnderline(False)
        self.trackingTitle_3.setFont(font1)
        self.trackingTitle_3.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle_3.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle_3.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget = QWidget(self.frame_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 50, 351, 511))
        self.verticalLayout_11 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.threshold_5 = QLabel(self.layoutWidget)
        self.threshold_5.setObjectName(u"threshold_5")
        font2 = QFont()
        font2.setPointSize(12)
        self.threshold_5.setFont(font2)
        self.threshold_5.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_5.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_5.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.threshold_5)

        self.threshold_6 = QLabel(self.layoutWidget)
        self.threshold_6.setObjectName(u"threshold_6")
        self.threshold_6.setMinimumSize(QSize(0, 0))
        self.threshold_6.setMaximumSize(QSize(50, 16777215))
        self.threshold_6.setFont(font2)
        self.threshold_6.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.threshold_6.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_6.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_6.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.threshold_6)

        self.invertToggle = QCheckBox(self.layoutWidget)
        self.invertToggle.setObjectName(u"invertToggle")
        self.invertToggle.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_2.addWidget(self.invertToggle)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.thresholdToggle = QCheckBox(self.layoutWidget)
        self.thresholdToggle.setObjectName(u"thresholdToggle")
        self.thresholdToggle.setFont(font2)
        self.thresholdToggle.setCheckable(True)

        self.horizontalLayout_13.addWidget(self.thresholdToggle)

        self.thresholdSlider = QSlider(self.layoutWidget)
        self.thresholdSlider.setObjectName(u"thresholdSlider")
        self.thresholdSlider.setEnabled(False)
        self.thresholdSlider.setMaximum(100)
        self.thresholdSlider.setOrientation(Qt.Orientation.Horizontal)
        self.thresholdSlider.setInvertedAppearance(False)
        self.thresholdSlider.setInvertedControls(False)
        self.thresholdSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.thresholdSlider.setTickInterval(10)

        self.horizontalLayout_13.addWidget(self.thresholdSlider)

        self.thresholdValue = QSpinBox(self.layoutWidget)
        self.thresholdValue.setObjectName(u"thresholdValue")
        self.thresholdValue.setEnabled(False)
        self.thresholdValue.setMinimumSize(QSize(100, 0))
        self.thresholdValue.setFont(font2)
        self.thresholdValue.setMaximum(100)

        self.horizontalLayout_13.addWidget(self.thresholdValue)


        self.verticalLayout_2.addLayout(self.horizontalLayout_13)


        self.verticalLayout_11.addLayout(self.verticalLayout_2)

        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.contour_2 = QLabel(self.layoutWidget)
        self.contour_2.setObjectName(u"contour_2")
        self.contour_2.setFont(font2)
        self.contour_2.setFrameShape(QFrame.Shape.NoFrame)
        self.contour_2.setFrameShadow(QFrame.Shadow.Raised)
        self.contour_2.setTextFormat(Qt.TextFormat.RichText)
        self.contour_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_10.addWidget(self.contour_2)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.contourToggle = QCheckBox(self.layoutWidget)
        self.contourToggle.setObjectName(u"contourToggle")
        self.contourToggle.setFont(font2)

        self.horizontalLayout_12.addWidget(self.contourToggle)

        self.contourSlider = QSlider(self.layoutWidget)
        self.contourSlider.setObjectName(u"contourSlider")
        self.contourSlider.setEnabled(False)
        self.contourSlider.setFont(font2)
        self.contourSlider.setMinimum(-100)
        self.contourSlider.setMaximum(100)
        self.contourSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contourSlider.setInvertedAppearance(False)
        self.contourSlider.setInvertedControls(False)
        self.contourSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contourSlider.setTickInterval(10)

        self.horizontalLayout_12.addWidget(self.contourSlider)

        self.contourValue = QSpinBox(self.layoutWidget)
        self.contourValue.setObjectName(u"contourValue")
        self.contourValue.setEnabled(False)
        self.contourValue.setMinimumSize(QSize(100, 0))
        self.contourValue.setFont(font2)
        self.contourValue.setMinimum(-100)
        self.contourValue.setMaximum(100)

        self.horizontalLayout_12.addWidget(self.contourValue)


        self.verticalLayout_10.addLayout(self.horizontalLayout_12)


        self.verticalLayout_11.addLayout(self.verticalLayout_10)

        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.contrast_2 = QLabel(self.layoutWidget)
        self.contrast_2.setObjectName(u"contrast_2")
        self.contrast_2.setFont(font2)
        self.contrast_2.setFrameShape(QFrame.Shape.NoFrame)
        self.contrast_2.setFrameShadow(QFrame.Shadow.Raised)
        self.contrast_2.setTextFormat(Qt.TextFormat.RichText)
        self.contrast_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_9.addWidget(self.contrast_2)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.contrastToggle = QCheckBox(self.layoutWidget)
        self.contrastToggle.setObjectName(u"contrastToggle")
        self.contrastToggle.setFont(font2)

        self.horizontalLayout_11.addWidget(self.contrastToggle)

        self.contrastSlider = QSlider(self.layoutWidget)
        self.contrastSlider.setObjectName(u"contrastSlider")
        self.contrastSlider.setEnabled(False)
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contrastSlider.setInvertedAppearance(False)
        self.contrastSlider.setInvertedControls(False)
        self.contrastSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contrastSlider.setTickInterval(10)

        self.horizontalLayout_11.addWidget(self.contrastSlider)

        self.contrastValue = QSpinBox(self.layoutWidget)
        self.contrastValue.setObjectName(u"contrastValue")
        self.contrastValue.setEnabled(False)
        self.contrastValue.setMinimumSize(QSize(100, 0))
        self.contrastValue.setFont(font2)
        self.contrastValue.setMinimum(-100)
        self.contrastValue.setMaximum(100)

        self.horizontalLayout_11.addWidget(self.contrastValue)


        self.verticalLayout_9.addLayout(self.horizontalLayout_11)


        self.verticalLayout_11.addLayout(self.verticalLayout_9)

        self.verticalLayout_16 = QVBoxLayout()
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.blurTitle_2 = QLabel(self.layoutWidget)
        self.blurTitle_2.setObjectName(u"blurTitle_2")
        self.blurTitle_2.setFont(font2)
        self.blurTitle_2.setFrameShape(QFrame.Shape.NoFrame)
        self.blurTitle_2.setFrameShadow(QFrame.Shadow.Raised)
        self.blurTitle_2.setTextFormat(Qt.TextFormat.RichText)
        self.blurTitle_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_16.addWidget(self.blurTitle_2)

        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.blurToggle = QCheckBox(self.layoutWidget)
        self.blurToggle.setObjectName(u"blurToggle")
        self.blurToggle.setFont(font2)

        self.horizontalLayout_15.addWidget(self.blurToggle)

        self.blurSlider = QSlider(self.layoutWidget)
        self.blurSlider.setObjectName(u"blurSlider")
        self.blurSlider.setEnabled(False)
        self.blurSlider.setMaximum(100)
        self.blurSlider.setOrientation(Qt.Orientation.Horizontal)
        self.blurSlider.setInvertedAppearance(False)
        self.blurSlider.setInvertedControls(False)
        self.blurSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.blurSlider.setTickInterval(10)

        self.horizontalLayout_15.addWidget(self.blurSlider)

        self.blurValue = QSpinBox(self.layoutWidget)
        self.blurValue.setObjectName(u"blurValue")
        self.blurValue.setEnabled(False)
        self.blurValue.setMinimumSize(QSize(100, 0))
        self.blurValue.setFont(font2)
        self.blurValue.setMaximum(100)
        self.blurValue.setDisplayIntegerBase(10)

        self.horizontalLayout_15.addWidget(self.blurValue)


        self.verticalLayout_16.addLayout(self.horizontalLayout_15)


        self.verticalLayout_11.addLayout(self.verticalLayout_16)

        self.verticalLayout_14 = QVBoxLayout()
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.dilationTitle_3 = QLabel(self.layoutWidget)
        self.dilationTitle_3.setObjectName(u"dilationTitle_3")
        self.dilationTitle_3.setFont(font2)
        self.dilationTitle_3.setFrameShape(QFrame.Shape.NoFrame)
        self.dilationTitle_3.setFrameShadow(QFrame.Shadow.Raised)
        self.dilationTitle_3.setTextFormat(Qt.TextFormat.RichText)
        self.dilationTitle_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_14.addWidget(self.dilationTitle_3)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.dilationToggle = QCheckBox(self.layoutWidget)
        self.dilationToggle.setObjectName(u"dilationToggle")
        self.dilationToggle.setFont(font2)

        self.horizontalLayout_16.addWidget(self.dilationToggle)

        self.dilationSlider = QSlider(self.layoutWidget)
        self.dilationSlider.setObjectName(u"dilationSlider")
        self.dilationSlider.setEnabled(False)
        self.dilationSlider.setMinimum(0)
        self.dilationSlider.setMaximum(5)
        self.dilationSlider.setPageStep(1)
        self.dilationSlider.setOrientation(Qt.Orientation.Horizontal)
        self.dilationSlider.setInvertedAppearance(False)
        self.dilationSlider.setInvertedControls(False)
        self.dilationSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.dilationSlider.setTickInterval(1)

        self.horizontalLayout_16.addWidget(self.dilationSlider)

        self.dilationValue = QSpinBox(self.layoutWidget)
        self.dilationValue.setObjectName(u"dilationValue")
        self.dilationValue.setEnabled(False)
        self.dilationValue.setMinimumSize(QSize(100, 0))
        self.dilationValue.setFont(font2)
        self.dilationValue.setMinimum(0)
        self.dilationValue.setMaximum(5)
        self.dilationValue.setDisplayIntegerBase(10)

        self.horizontalLayout_16.addWidget(self.dilationValue)


        self.verticalLayout_14.addLayout(self.horizontalLayout_16)


        self.verticalLayout_11.addLayout(self.verticalLayout_14)

        self.verticalLayout_15 = QVBoxLayout()
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.dilationTitle_4 = QLabel(self.layoutWidget)
        self.dilationTitle_4.setObjectName(u"dilationTitle_4")
        self.dilationTitle_4.setFont(font2)
        self.dilationTitle_4.setFrameShape(QFrame.Shape.NoFrame)
        self.dilationTitle_4.setFrameShadow(QFrame.Shadow.Raised)
        self.dilationTitle_4.setTextFormat(Qt.TextFormat.RichText)
        self.dilationTitle_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_15.addWidget(self.dilationTitle_4)

        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.medianToggle = QCheckBox(self.layoutWidget)
        self.medianToggle.setObjectName(u"medianToggle")
        self.medianToggle.setFont(font2)

        self.horizontalLayout_17.addWidget(self.medianToggle)

        self.medianSlider = QSlider(self.layoutWidget)
        self.medianSlider.setObjectName(u"medianSlider")
        self.medianSlider.setEnabled(False)
        self.medianSlider.setMinimum(0)
        self.medianSlider.setMaximum(30)
        self.medianSlider.setPageStep(1)
        self.medianSlider.setOrientation(Qt.Orientation.Horizontal)
        self.medianSlider.setInvertedAppearance(False)
        self.medianSlider.setInvertedControls(False)
        self.medianSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.medianSlider.setTickInterval(1)

        self.horizontalLayout_17.addWidget(self.medianSlider)

        self.medianValue = QSpinBox(self.layoutWidget)
        self.medianValue.setObjectName(u"medianValue")
        self.medianValue.setEnabled(False)
        self.medianValue.setMinimumSize(QSize(100, 0))
        self.medianValue.setFont(font2)
        self.medianValue.setMinimum(0)
        self.medianValue.setMaximum(30)
        self.medianValue.setDisplayIntegerBase(10)

        self.horizontalLayout_17.addWidget(self.medianValue)


        self.verticalLayout_15.addLayout(self.horizontalLayout_17)


        self.verticalLayout_11.addLayout(self.verticalLayout_15)

        self.testButton = QPushButton(self.frame_2)
        self.testButton.setObjectName(u"testButton")
        self.testButton.setGeometry(QRect(20, 490, 75, 24))

        self.horizontalLayout_3.addWidget(self.frame_2)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.frame_4 = QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy1.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy1)
        self.frame_4.setMinimumSize(QSize(660, 270))
        self.frame_4.setMaximumSize(QSize(660, 270))
        self.frame_4.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_7 = QFrame(self.frame_4)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 10, 641, 31))
        sizePolicy1.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy1)
        self.frame_7.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.consoleOutputTitle = QLabel(self.frame_7)
        self.consoleOutputTitle.setObjectName(u"consoleOutputTitle")
        self.consoleOutputTitle.setGeometry(QRect(0, 0, 641, 31))
        self.consoleOutputTitle.setFont(font)
        self.consoleOutputTitle.setFrameShape(QFrame.Shape.NoFrame)
        self.consoleOutputTitle.setFrameShadow(QFrame.Shadow.Raised)
        self.consoleOutputTitle.setTextFormat(Qt.TextFormat.RichText)
        self.consoleOutputTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.output = QTabWidget(self.frame_4)
        self.output.setObjectName(u"output")
        self.output.setGeometry(QRect(10, 50, 641, 211))
        self.output.setTabPosition(QTabWidget.TabPosition.North)
        self.output.setTabShape(QTabWidget.TabShape.Rounded)
        self.output.setElideMode(Qt.TextElideMode.ElideNone)
        self.output.setDocumentMode(False)
        self.output.setTabsClosable(False)
        self.output.setMovable(True)
        self.output.setTabBarAutoHide(False)
        self.Console = QWidget()
        self.Console.setObjectName(u"Console")
        self.printOutput = QTextBrowser(self.Console)
        self.printOutput.setObjectName(u"printOutput")
        self.printOutput.setGeometry(QRect(0, 0, 635, 194))
        self.printOutput.setAcceptDrops(False)
        self.printOutput.setOpenLinks(False)
        self.output.addTab(self.Console, "")
        self.Summary = QWidget()
        self.Summary.setObjectName(u"Summary")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Summary.sizePolicy().hasHeightForWidth())
        self.Summary.setSizePolicy(sizePolicy3)
        self.summaryPlot = PlotWidget(self.Summary)
        self.summaryPlot.setObjectName(u"summaryPlot")
        self.summaryPlot.setGeometry(QRect(0, 0, 635, 181))
        self.output.addTab(self.Summary, "")
        self.horizontalLayoutWidget = QWidget(self.frame_4)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(410, 40, 236, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.showA = QLabel(self.horizontalLayoutWidget)
        self.showA.setObjectName(u"showA")
        self.showA.setEnabled(False)
        self.showA.setFont(font2)
        self.showA.setFrameShape(QFrame.Shape.NoFrame)
        self.showA.setFrameShadow(QFrame.Shadow.Raised)
        self.showA.setTextFormat(Qt.TextFormat.RichText)
        self.showA.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.showA)

        self.aToggle = QCheckBox(self.horizontalLayoutWidget)
        self.aToggle.setObjectName(u"aToggle")
        self.aToggle.setEnabled(False)
        self.aToggle.setMaximumSize(QSize(16, 16777215))
        self.aToggle.setFont(font2)

        self.horizontalLayout.addWidget(self.aToggle)

        self.showR = QLabel(self.horizontalLayoutWidget)
        self.showR.setObjectName(u"showR")
        self.showR.setEnabled(False)
        self.showR.setFont(font2)
        self.showR.setFrameShape(QFrame.Shape.NoFrame)
        self.showR.setFrameShadow(QFrame.Shadow.Raised)
        self.showR.setTextFormat(Qt.TextFormat.RichText)
        self.showR.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.showR)

        self.rToggle = QCheckBox(self.horizontalLayoutWidget)
        self.rToggle.setObjectName(u"rToggle")
        self.rToggle.setEnabled(False)
        self.rToggle.setMaximumSize(QSize(16, 16777215))
        self.rToggle.setFont(font2)

        self.horizontalLayout.addWidget(self.rToggle)

        self.showV = QLabel(self.horizontalLayoutWidget)
        self.showV.setObjectName(u"showV")
        self.showV.setEnabled(False)
        self.showV.setFont(font2)
        self.showV.setFrameShape(QFrame.Shape.NoFrame)
        self.showV.setFrameShadow(QFrame.Shadow.Raised)
        self.showV.setTextFormat(Qt.TextFormat.RichText)
        self.showV.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.showV)

        self.vToggle = QCheckBox(self.horizontalLayoutWidget)
        self.vToggle.setObjectName(u"vToggle")
        self.vToggle.setEnabled(False)
        self.vToggle.setMaximumSize(QSize(16, 16777215))
        self.vToggle.setFont(font2)

        self.horizontalLayout.addWidget(self.vToggle)

        self.kalmanFilter = QLabel(self.horizontalLayoutWidget)
        self.kalmanFilter.setObjectName(u"kalmanFilter")
        self.kalmanFilter.setEnabled(False)
        self.kalmanFilter.setFont(font2)
        self.kalmanFilter.setFrameShape(QFrame.Shape.NoFrame)
        self.kalmanFilter.setFrameShadow(QFrame.Shadow.Raised)
        self.kalmanFilter.setTextFormat(Qt.TextFormat.RichText)
        self.kalmanFilter.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.kalmanFilter)

        self.kalmanToggle = QCheckBox(self.horizontalLayoutWidget)
        self.kalmanToggle.setObjectName(u"kalmanToggle")
        self.kalmanToggle.setEnabled(False)
        self.kalmanToggle.setMaximumSize(QSize(16, 16777215))
        self.kalmanToggle.setFont(font2)

        self.horizontalLayout.addWidget(self.kalmanToggle)


        self.horizontalLayout_14.addWidget(self.frame_4)

        self.frame_3 = QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy1.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy1)
        self.frame_3.setMinimumSize(QSize(370, 270))
        self.frame_3.setMaximumSize(QSize(370, 270))
        self.frame_3.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(8)
        self.frame_5 = QFrame(self.frame_3)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 10, 347, 31))
        sizePolicy1.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy1)
        self.frame_5.setFrameShape(QFrame.Shape.WinPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.trackingTitle = QLabel(self.frame_5)
        self.trackingTitle.setObjectName(u"trackingTitle")
        self.trackingTitle.setGeometry(QRect(0, 0, 347, 31))
        sizePolicy1.setHeightForWidth(self.trackingTitle.sizePolicy().hasHeightForWidth())
        self.trackingTitle.setSizePolicy(sizePolicy1)
        self.trackingTitle.setFont(font1)
        self.trackingTitle.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.trackingTitle.setFrameShape(QFrame.Shape.NoFrame)
        self.trackingTitle.setFrameShadow(QFrame.Shadow.Raised)
        self.trackingTitle.setTextFormat(Qt.TextFormat.RichText)
        self.trackingTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.verticalLayoutWidget_3 = QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 50, 351, 211))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.threshold_2 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_2.setObjectName(u"threshold_2")
        self.threshold_2.setFont(font2)
        self.threshold_2.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_2.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_2.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_7.addWidget(self.threshold_2)

        self.subBackMethod = QComboBox(self.verticalLayoutWidget_3)
        self.subBackMethod.addItem("")
        self.subBackMethod.addItem("")
        self.subBackMethod.setObjectName(u"subBackMethod")
        self.subBackMethod.setEnabled(False)
        self.subBackMethod.setMaximumSize(QSize(75, 16777215))

        self.horizontalLayout_7.addWidget(self.subBackMethod)


        self.verticalLayout_5.addLayout(self.horizontalLayout_7)

        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.subBackToggle = QCheckBox(self.verticalLayoutWidget_3)
        self.subBackToggle.setObjectName(u"subBackToggle")
        self.subBackToggle.setFont(font2)

        self.horizontalLayout_4.addWidget(self.subBackToggle)

        self.subBackSlider = QSlider(self.verticalLayoutWidget_3)
        self.subBackSlider.setObjectName(u"subBackSlider")
        self.subBackSlider.setEnabled(False)
        self.subBackSlider.setMaximum(100)
        self.subBackSlider.setOrientation(Qt.Orientation.Horizontal)
        self.subBackSlider.setInvertedAppearance(False)
        self.subBackSlider.setInvertedControls(False)
        self.subBackSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.subBackSlider.setTickInterval(10)

        self.horizontalLayout_4.addWidget(self.subBackSlider)

        self.subBackValue = QSpinBox(self.verticalLayoutWidget_3)
        self.subBackValue.setObjectName(u"subBackValue")
        self.subBackValue.setEnabled(False)
        self.subBackValue.setMinimumSize(QSize(100, 0))
        self.subBackValue.setFont(font2)
        self.subBackValue.setMaximum(100)

        self.horizontalLayout_4.addWidget(self.subBackValue)


        self.verticalLayout_6.addLayout(self.horizontalLayout_4)


        self.verticalLayout_5.addLayout(self.verticalLayout_6)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.threshold_3 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_3.setObjectName(u"threshold_3")
        self.threshold_3.setFont(font2)
        self.threshold_3.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_3.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_3.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_8.addWidget(self.threshold_3)

        self.cf = QLabel(self.verticalLayoutWidget_3)
        self.cf.setObjectName(u"cf")
        self.cf.setEnabled(False)
        self.cf.setMaximumSize(QSize(20, 16777215))
        self.cf.setFont(font2)
        self.cf.setFrameShape(QFrame.Shape.NoFrame)
        self.cf.setFrameShadow(QFrame.Shadow.Raised)
        self.cf.setTextFormat(Qt.TextFormat.RichText)
        self.cf.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.cf)

        self.consecutiveFramesValue = QSpinBox(self.verticalLayoutWidget_3)
        self.consecutiveFramesValue.setObjectName(u"consecutiveFramesValue")
        self.consecutiveFramesValue.setEnabled(False)
        self.consecutiveFramesValue.setMinimumSize(QSize(75, 0))
        self.consecutiveFramesValue.setMaximumSize(QSize(75, 16777215))
        self.consecutiveFramesValue.setFont(font2)
        self.consecutiveFramesValue.setMinimum(1)
        self.consecutiveFramesValue.setMaximum(100)
        self.consecutiveFramesValue.setValue(12)

        self.horizontalLayout_8.addWidget(self.consecutiveFramesValue)


        self.verticalLayout_5.addLayout(self.horizontalLayout_8)

        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frameDiffToggle = QCheckBox(self.verticalLayoutWidget_3)
        self.frameDiffToggle.setObjectName(u"frameDiffToggle")
        self.frameDiffToggle.setFont(font2)

        self.horizontalLayout_5.addWidget(self.frameDiffToggle)

        self.frameDiffSlider = QSlider(self.verticalLayoutWidget_3)
        self.frameDiffSlider.setObjectName(u"frameDiffSlider")
        self.frameDiffSlider.setEnabled(False)
        self.frameDiffSlider.setMinimum(0)
        self.frameDiffSlider.setMaximum(1000)
        self.frameDiffSlider.setValue(25)
        self.frameDiffSlider.setOrientation(Qt.Orientation.Horizontal)
        self.frameDiffSlider.setInvertedAppearance(False)
        self.frameDiffSlider.setInvertedControls(False)
        self.frameDiffSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.frameDiffSlider.setTickInterval(10)

        self.horizontalLayout_5.addWidget(self.frameDiffSlider)

        self.frameDiffValue = QSpinBox(self.verticalLayoutWidget_3)
        self.frameDiffValue.setObjectName(u"frameDiffValue")
        self.frameDiffValue.setEnabled(False)
        self.frameDiffValue.setMinimumSize(QSize(100, 0))
        self.frameDiffValue.setFont(font2)
        self.frameDiffValue.setMinimum(0)
        self.frameDiffValue.setMaximum(1000)
        self.frameDiffValue.setValue(25)

        self.horizontalLayout_5.addWidget(self.frameDiffValue)


        self.verticalLayout_7.addLayout(self.horizontalLayout_5)


        self.verticalLayout_5.addLayout(self.verticalLayout_7)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.threshold_4 = QLabel(self.verticalLayoutWidget_3)
        self.threshold_4.setObjectName(u"threshold_4")
        self.threshold_4.setFont(font2)
        self.threshold_4.setFrameShape(QFrame.Shape.NoFrame)
        self.threshold_4.setFrameShadow(QFrame.Shadow.Raised)
        self.threshold_4.setTextFormat(Qt.TextFormat.RichText)
        self.threshold_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_9.addWidget(self.threshold_4)


        self.verticalLayout_5.addLayout(self.horizontalLayout_9)

        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.contDetectSlider = QSlider(self.verticalLayoutWidget_3)
        self.contDetectSlider.setObjectName(u"contDetectSlider")
        self.contDetectSlider.setEnabled(False)
        self.contDetectSlider.setFont(font2)
        self.contDetectSlider.setMaximum(150)
        self.contDetectSlider.setSingleStep(1)
        self.contDetectSlider.setPageStep(10)
        self.contDetectSlider.setValue(30)
        self.contDetectSlider.setOrientation(Qt.Orientation.Horizontal)
        self.contDetectSlider.setInvertedAppearance(False)
        self.contDetectSlider.setInvertedControls(False)
        self.contDetectSlider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.contDetectSlider.setTickInterval(10)

        self.horizontalLayout_6.addWidget(self.contDetectSlider)

        self.contDetectValue = QSpinBox(self.verticalLayoutWidget_3)
        self.contDetectValue.setObjectName(u"contDetectValue")
        self.contDetectValue.setEnabled(False)
        self.contDetectValue.setMinimumSize(QSize(100, 0))
        self.contDetectValue.setFont(font2)
        self.contDetectValue.setMaximum(150)
        self.contDetectValue.setValue(30)

        self.horizontalLayout_6.addWidget(self.contDetectValue)


        self.verticalLayout_8.addLayout(self.horizontalLayout_6)


        self.verticalLayout_5.addLayout(self.verticalLayout_8)


        self.horizontalLayout_14.addWidget(self.frame_3)


        self.verticalLayout.addLayout(self.horizontalLayout_14)


        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_4.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1091, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuClear = QMenu(self.menubar)
        self.menuClear.setObjectName(u"menuClear")
        self.menuClear.setTearOffEnabled(False)
        self.menuScale_Bar = QMenu(self.menuClear)
        self.menuScale_Bar.setObjectName(u"menuScale_Bar")
        self.menuMain = QMenu(self.menubar)
        self.menuMain.setObjectName(u"menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menuMain.menuAction())
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionSave)
        self.menuClear.addAction(self.actionClear)
        self.menuClear.addAction(self.menuScale_Bar.menuAction())
        self.menuClear.addAction(self.actionFPS)
        self.menuClear.addAction(self.actionDetails)
        self.menuClear.addAction(self.actionMedian_Velocity_2)
        self.menuClear.addAction(self.actionLock_Size)
        self.menuScale_Bar.addAction(self.actionEdit)
        self.menuScale_Bar.addAction(self.actionShow)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionPoints_2)
        self.menuMain.addAction(self.actionBounding_Boxes_2)
        self.menuMain.addAction(self.actionOriginal_Frame)
        self.menuMain.addAction(self.actionDirection)
        self.menuMain.addAction(self.actionSpeed)
        self.menuMain.addAction(self.actionAngular_Velocity)
        self.menuMain.addAction(self.actionAlignment_Angle)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionCollate_Data_NPM)

        self.retranslateUi(MainWindow)
        self.frameDiffToggle.toggled.connect(self.frameDiffValue.setEnabled)
        self.subBackToggle.toggled.connect(self.subBackMethod.setEnabled)
        self.frameDiffValue.valueChanged.connect(self.frameDiffSlider.setValue)
        self.frameDiffToggle.toggled.connect(self.consecutiveFramesValue.setEnabled)
        self.subBackToggle.toggled.connect(self.subBackValue.setEnabled)
        self.subBackSlider.valueChanged.connect(self.subBackValue.setValue)
        self.subBackToggle.toggled.connect(self.subBackSlider.setEnabled)
        self.frameDiffToggle.toggled.connect(self.frameDiffSlider.setEnabled)
        self.frameDiffToggle.toggled.connect(self.cf.setEnabled)
        self.frameDiffSlider.valueChanged.connect(self.frameDiffValue.setValue)
        self.subBackValue.valueChanged.connect(self.subBackSlider.setValue)
        self.record.toggled.connect(self.kalmanFilter.setEnabled)
        self.record.toggled.connect(self.contDetectSlider.setEnabled)
        self.record.toggled.connect(self.kalmanToggle.setEnabled)
        self.record.toggled.connect(self.contDetectValue.setEnabled)

        self.output.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen_Video.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.actionPoints.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.actionPoints_2.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.actionBounding_Boxes_2.setText(QCoreApplication.translate("MainWindow", u"Bounding Boxes", None))
        self.actionFPS.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.actionOriginal_Frame.setText(QCoreApplication.translate("MainWindow", u"Original Frame", None))
        self.actionCollate_Data_NPM.setText(QCoreApplication.translate("MainWindow", u"Collate by Voltage (NPM only)", None))
        self.actionDetails.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        self.actionDirection.setText(QCoreApplication.translate("MainWindow", u"Arrows", None))
        self.actionSpeed.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.actionAngular_Velocity.setText(QCoreApplication.translate("MainWindow", u"Angular Velocity", None))
        self.actionMedian_Velocity.setText(QCoreApplication.translate("MainWindow", u"Median Velocity", None))
        self.actionMedian_Velocity_2.setText(QCoreApplication.translate("MainWindow", u"Median Velocity", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionShow.setText(QCoreApplication.translate("MainWindow", u"Show", None))
        self.actionLock_Size.setText(QCoreApplication.translate("MainWindow", u"Lock Size", None))
        self.actionAlignment_Angle.setText(QCoreApplication.translate("MainWindow", u"Alignment Angle", None))
        self.trackingTitle_2.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.video_1.setText("")
        self.record.setText(QCoreApplication.translate("MainWindow", u"Record Data", None))
        self.trackingTitle_3.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.threshold_5.setText(QCoreApplication.translate("MainWindow", u"Threshold", None))
        self.threshold_6.setText(QCoreApplication.translate("MainWindow", u"Invert", None))
        self.invertToggle.setText("")
        self.thresholdToggle.setText("")
        self.contour_2.setText(QCoreApplication.translate("MainWindow", u"Emboss", None))
        self.contourToggle.setText("")
        self.contrast_2.setText(QCoreApplication.translate("MainWindow", u"Contrast", None))
        self.contrastToggle.setText("")
        self.blurTitle_2.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.blurToggle.setText("")
        self.dilationTitle_3.setText(QCoreApplication.translate("MainWindow", u"Dilation", None))
        self.dilationToggle.setText("")
        self.dilationTitle_4.setText(QCoreApplication.translate("MainWindow", u"Average Frame Filtering", None))
        self.medianToggle.setText("")
        self.testButton.setText(QCoreApplication.translate("MainWindow", u"Test!", None))
        self.consoleOutputTitle.setText(QCoreApplication.translate("MainWindow", u"Output", None))
        self.output.setTabText(self.output.indexOf(self.Console), QCoreApplication.translate("MainWindow", u"Console", None))
        self.output.setTabText(self.output.indexOf(self.Summary), QCoreApplication.translate("MainWindow", u"Summary", None))
        self.showA.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.aToggle.setText("")
        self.showR.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.rToggle.setText("")
        self.showV.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.vToggle.setText("")
        self.kalmanFilter.setText(QCoreApplication.translate("MainWindow", u"Kalman Filter", None))
        self.kalmanToggle.setText("")
        self.trackingTitle.setText(QCoreApplication.translate("MainWindow", u"Detection", None))
        self.threshold_2.setText(QCoreApplication.translate("MainWindow", u"Subtract Background", None))
        self.subBackMethod.setItemText(0, QCoreApplication.translate("MainWindow", u"KNN", None))
        self.subBackMethod.setItemText(1, QCoreApplication.translate("MainWindow", u"MOG2", None))

        self.subBackToggle.setText("")
        self.threshold_3.setText(QCoreApplication.translate("MainWindow", u"Frame Differencing", None))
        self.cf.setText(QCoreApplication.translate("MainWindow", u"CF", None))
        self.frameDiffToggle.setText("")
        self.threshold_4.setText(QCoreApplication.translate("MainWindow", u"Persistence (frames)", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuClear.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuScale_Bar.setTitle(QCoreApplication.translate("MainWindow", u"Scale Bar", None))
        self.menuMain.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

